# Generated by Django 4.1 on 2022-09-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(null=True)),
                ('slug', models.SlugField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CW', 'Casement window'), ('FW', 'Fix window'), ('SW', 'Sliding window')], default='FW', max_length=2)),
                ('reference_name', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField(default=1000, validators=[shop.validators.width_validator])),
                ('height', models.PositiveIntegerField(default=1000, validators=[shop.validators.height_validator])),
                ('price', models.FloatField(null=True)),
                ('color', models.CharField(choices=[('7016', 'Antracite'), ('9006', 'Silver'), ('8017', 'Brown'), ('9016', 'White'), ('9005', 'Black')], default='9016', max_length=4)),
                ('slug', models.SlugField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_project', to='shop.project')),
            ],
        ),
    ]
