# Generated by Django 4.1 on 2022-09-01 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SW', 'Sliding window'), ('FW', 'Fix window'), ('CW', 'Casement window')], default='FW', max_length=2)),
                ('reference_name', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField(default=1000, validators=[shop.validators.width_validator])),
                ('height', models.PositiveIntegerField(default=1000, validators=[shop.validators.height_validator])),
                ('price', models.FloatField()),
                ('color', models.CharField(choices=[('9005', 'Black'), ('7016', 'Antracite'), ('9016', 'White'), ('8017', 'Brown'), ('9006', 'Silver')], default='9016', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.construction')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='shop.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
