# Generated by Django 4.1 on 2022-08-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('DW', 'Double window'), ('SW', 'Single window'), ('LS', 'Lift-slide window'), ('FW', 'fix window')], default='FW', max_length=2),
        ),
        migrations.AddField(
            model_name='construction',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
        ),
    ]
