# Generated by Django 4.1 on 2022-08-25 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('SW', 'Sliding window'), ('CW', 'Casement window'), ('FW', 'Fix window')], default='FW', max_length=2),
        ),
        migrations.AddField(
            model_name='construction',
            name='color',
            field=models.CharField(choices=[('9006', 'Silver'), ('8017', 'Brown'), ('9005', 'Black'), ('9016', 'White'), ('7016', 'Antracite')], default='9016', max_length=4),
        ),
        migrations.AddField(
            model_name='construction',
            name='height',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(350)]),
        ),
        migrations.AddField(
            model_name='construction',
            name='slug',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construction',
            name='width',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(350)]),
        ),
    ]
