# Generated by Django 4.1 on 2022-08-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_construction_category_construction_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('FW', 'fix window'), ('SW', 'Single window'), ('LS', 'Lift-slide window'), ('DW', 'Double window')], default='FW', max_length=2),
        ),
        migrations.AlterField(
            model_name='construction',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], default='P', max_length=1),
        ),
    ]
