# Generated by Django 4.1 on 2022-09-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_construction_category_alter_construction_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='color',
            field=models.CharField(choices=[('9016', 'White'), ('9005', 'Black'), ('7016', 'Antracite'), ('9006', 'Silver'), ('8017', 'Brown')], default='9016', max_length=4),
        ),
    ]
