# Generated by Django 4.1 on 2022-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_construction_category_alter_construction_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('FW', 'Fix window'), ('SW', 'Sliding window'), ('CW', 'Casement window')], default='FW', max_length=2),
        ),
        migrations.AlterField(
            model_name='construction',
            name='color',
            field=models.CharField(choices=[('7016', 'Antracite'), ('8017', 'Brown'), ('9016', 'White'), ('9005', 'Black'), ('9006', 'Silver')], default='9016', max_length=4),
        ),
    ]
