# Generated by Django 4.1 on 2022-08-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_construction_slug_alter_construction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('FW', 'fix window'), ('LS', 'Lift-slide window'), ('DW', 'Double window'), ('SW', 'Single window')], default='FW', max_length=2),
        ),
        migrations.AlterField(
            model_name='construction',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
        ),
    ]
