# Generated by Django 4.1 on 2022-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_construction_category_alter_construction_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='color',
            field=models.CharField(choices=[('9016', 'White'), ('7016', 'Antracite'), ('9005', 'Black'), ('8017', 'Brown'), ('9006', 'Silver')], default='9016', max_length=4),
        ),
    ]
