# Generated by Django 4.1 on 2022-08-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_construction_category_alter_construction_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('DW', 'Double window'), ('FW', 'fix window'), ('SW', 'Single window'), ('LS', 'Lift-slide window')], default='FW', max_length=2),
        ),
        migrations.AlterField(
            model_name='construction',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('P', 'primary'), ('S', 'secondary')], default='P', max_length=1),
        ),
    ]
