# Generated by Django 4.1 on 2022-08-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_construction_category_alter_construction_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('FW', 'fix window'), ('CW', 'Casement window'), ('SW', 'Sliding window')], default='FW', max_length=2),
        ),
    ]
