# Generated by Django 4.1 on 2022-08-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_construction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('CW', 'Casement window'), ('FW', 'Fix window'), ('SW', 'Sliding window')], default='FW', max_length=2),
        ),
        migrations.AlterField(
            model_name='construction',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], default='P', max_length=1),
        ),
    ]
