# Generated by Django 4.1 on 2022-08-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_construction_label_construction_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='color',
            field=models.CharField(choices=[('9005', 'Black'), ('9006', 'Silver'), ('7016', 'Antracite'), ('9016', 'White'), ('8017', 'Brown')], default='9016', max_length=4),
        ),
    ]
