# Generated by Django 4.1 on 2022-09-06 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_alter_construction_category_alter_construction_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.AlterField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('CW', 'Casement window'), ('FW', 'Fix window'), ('SW', 'Sliding window')], default='FW', max_length=2),
        ),
        migrations.AlterField(
            model_name='construction',
            name='color',
            field=models.CharField(choices=[('9006', 'Silver'), ('8017', 'Brown'), ('9005', 'Black'), ('7016', 'Antracite'), ('9016', 'White')], default='9016', max_length=4),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='project',
            name='constructions',
            field=models.ManyToManyField(to='shop.construction'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
