# Generated by Django 4.1 on 2022-09-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_project_remove_orderitem_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='constructions',
        ),
        migrations.AddField(
            model_name='construction',
            name='project_name',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='shop.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('SW', 'Sliding window'), ('FW', 'Fix window'), ('CW', 'Casement window')], default='FW', max_length=2),
        ),
        migrations.AlterField(
            model_name='construction',
            name='color',
            field=models.CharField(choices=[('9016', 'White'), ('9005', 'Black'), ('8017', 'Brown'), ('7016', 'Antracite'), ('9006', 'Silver')], default='9016', max_length=4),
        ),
    ]
