# Generated by Django 4.1 on 2022-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_project_constructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='proj_name',
            new_name='project_name',
        ),
        migrations.AlterField(
            model_name='construction',
            name='color',
            field=models.CharField(choices=[('9016', 'White'), ('7016', 'Antracite'), ('8017', 'Brown'), ('9006', 'Silver'), ('9005', 'Black')], default='9016', max_length=4),
        ),
    ]
