# Generated by Django 4.1 on 2022-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_project_name_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='category',
            field=models.CharField(choices=[('FW', 'Fix window'), ('SW', 'Sliding window'), ('CW', 'Casement window')], default='FW', max_length=2),
        ),
        migrations.AlterField(
            model_name='construction',
            name='color',
            field=models.CharField(choices=[('9005', 'Black'), ('7016', 'Antracite'), ('9016', 'White'), ('9006', 'Silver'), ('8017', 'Brown')], default='9016', max_length=4),
        ),
    ]
